destination: ./_site
auto:        true
lsi:         false
server_port: 4567
pygments:    false
markdown:    maruku
permalink:   date
exclude:     jekyll-epub
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex
